import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Sidebar from "./components/Sidebar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > {/* ✅ FULL WIDTH HEADER */}
      <div className="w-full bg-cyan-700 py-8 shadow-md mb-8">
        <div className="max-w-6xl mx-auto px-6">
          <h1 className="text-4xl font-bold text-white flex items-center gap-3">
       Srj Bone Setting Centre
          </h1>
          <p className="mt-1">Manage hospital patient records efficiently</p>
        </div>
      </div>

       <Sidebar />
        {children}
        
      </body>
    </html>
  );
}
